export enum CausaMermaVivero {
  PLAGA = 'PLAGA',
  ENFERMEDAD = 'ENFERMEDAD',
  SEQUIA = 'SEQUIA',
  DANO_FISICO = 'DANO_FISICO',
  MUERTE_NATURAL = 'MUERTE_NATURAL',
  DESCARTE_CALIDAD = 'DESCARTE_CALIDAD',
  OTRO = 'OTRO',
}
