export enum CausaDescartePreEmbolsado {
  NO_GERMINACION = 'NO_GERMINACION',
  NO_ENRAIZAMIENTO = 'NO_ENRAIZAMIENTO',
  CONTAMINACION = 'CONTAMINACION',
  PERDIDA_TOTAL_MATERIAL = 'PERDIDA_TOTAL_MATERIAL',
  MATERIAL_NO_VIABLE = 'MATERIAL_NO_VIABLE',
  DANO_PRE_EMBOLSADO = 'DANO_PRE_EMBOLSADO',
  OTRO = 'OTRO',
}
