/**
 * Motivo de una devolucion fisica de stock asignado desde una subcampania
 * hacia el vivero (RF-VIV-12). Espejo del enum de BD
 * public.motivo_devolucion_plantacion (migracion 027).
 */
export enum MotivoDevolucionPlantacion {
  SOBRANTE_OPERATIVO = 'SOBRANTE_OPERATIVO',
  ERROR_PLANIFICACION = 'ERROR_PLANIFICACION',
  CAMBIO_SUBCAMPANIA = 'CAMBIO_SUBCAMPANIA',
  CIERRE_SUBCAMPANIA = 'CIERRE_SUBCAMPANIA',
  PROBLEMAS_CALIDAD_LOTE = 'PROBLEMAS_CALIDAD_LOTE',
  CONDICIONES_CAMPO_NO_APTAS = 'CONDICIONES_CAMPO_NO_APTAS',
  ACCESO_RESTRINGIDO = 'ACCESO_RESTRINGIDO',
  CANCELACION_ACTIVIDAD = 'CANCELACION_ACTIVIDAD',
  REASIGNACION_PRIORIDAD = 'REASIGNACION_PRIORIDAD',
  OTRO = 'OTRO',
}
