export enum TipoEventoVivero {
  INICIO = 'INICIO',
  EMBOLSADO = 'EMBOLSADO',
  DESCARTE_PRE_EMBOLSADO = 'DESCARTE_PRE_EMBOLSADO',
  ADAPTABILIDAD = 'ADAPTABILIDAD',
  MERMA = 'MERMA',
  DESPACHO = 'DESPACHO',
  /** Entrada fisica por devolucion de stock asignado desde M3 (RN-VIV-48). */
  DEVOLUCION_PLANTACION = 'DEVOLUCION_PLANTACION',
  CIERRE_AUTOMATICO = 'CIERRE_AUTOMATICO',
}
