export enum TipoEventoVivero {
  INICIO = 'INICIO',
  EMBOLSADO = 'EMBOLSADO',
  ADAPTABILIDAD = 'ADAPTABILIDAD',
  MERMA = 'MERMA',
  DESPACHO = 'DESPACHO',
  CIERRE_AUTOMATICO = 'CIERRE_AUTOMATICO',
}
