export enum TipoOrganizacion {
  ONG = 'ONG',
  EMPRESA_PRIVADA = 'EMPRESA_PRIVADA',
  EMPRESA_PUBLICA = 'EMPRESA_PUBLICA',
  FUNDACION = 'FUNDACION',
  ETFs = 'ETFs',
  ALCALDIA = 'ALCALDIA',
  ASOCIACION_CIUDADANA = 'ASOCIACION_CIUDADANA',
  OTRO = 'OTRO',
}
