export enum EstadoSubcampania {
  BORRADOR = 'BORRADOR',
  ACTIVA = 'ACTIVA',
  COMPLETADA = 'COMPLETADA',
  FINALIZADA_PARCIAL = 'FINALIZADA_PARCIAL',
  PAUSADA = 'PAUSADA',
  CANCELADA = 'CANCELADA',
}
