export enum MotivoCierreParcial {
  FALTA_STOCK = 'FALTA_STOCK',
  PROBLEMAS_CLIMATICOS = 'PROBLEMAS_CLIMATICOS',
  CANCELACION_CONVENIO = 'CANCELACION_CONVENIO',
  CONFLICTO_SOCIAL = 'CONFLICTO_SOCIAL',
  ACCESO_RESTRINGIDO = 'ACCESO_RESTRINGIDO',
  CAMBIO_PRIORIDAD_INSTITUCIONAL = 'CAMBIO_PRIORIDAD_INSTITUCIONAL',
  RIESGO_OPERATIVO = 'RIESGO_OPERATIVO',
  META_REDEFINIDA = 'META_REDEFINIDA',
  CIERRE_ADMINISTRATIVO = 'CIERRE_ADMINISTRATIVO',
  OTRO = 'OTRO',
}
